# Generated by Django 3.1.5 on 2021-02-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_encuesta', models.CharField(default='Escribir el nombre de la encuesta', max_length=200)),
                ('texto_encuesta', models.TextField(default='Ingresar descripción de la encuesta.')),
                ('puntaje_total', models.IntegerField(default='Ingresar puntaje total de la encuesta.')),
            ],
        ),
        migrations.CreateModel(
            name='posee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importancia_pregunta', models.IntegerField(default='Ingresar peso de la pregunta en la encuesta. (En porcentaje: 20,30 etc)')),
                ('encuesta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta')),
                ('pregunta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='encuesta_topico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuesta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta')),
                ('topico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.topico')),
            ],
        ),
    ]
