# Generated by Django 3.1.5 on 2021-02-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil_wunder', '0001_initial'),
        ('perfil_cliente', '0001_initial'),
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha envío solicitud')),
                ('estado', models.CharField(default='Seleccione el estado de la pregunta solicitud', max_length=20)),
                ('puntaje_obtenido', models.DecimalField(decimal_places=3, max_digits=6)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_cliente.usuario_cliente')),
                ('id_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta')),
                ('id_wunder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_wunder.usuario_wunder')),
            ],
        ),
    ]
