# Generated by Django 3.1.5 on 2021-02-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField(default='Escribir Pregunta')),
                ('tipo_pregunta', models.TextField(default='Ingrese Tipo de pregunta')),
                ('alternativa', models.TextField(default='Ingrese las alternativas')),
                ('estado', models.CharField(default='Seleccione el estado de la pregunta', max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='topico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='Escribir el topico de la encuesta', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pregunta_topico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.pregunta')),
                ('topico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.topico')),
            ],
        ),
    ]
