# Generated by Django 3.1.5 on 2021-02-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(default='RUT de la empresa', max_length=20)),
                ('nombre', models.CharField(default='Nombre de la empresa', max_length=100)),
                ('telefono', models.CharField(default='Número de teléfono', max_length=20)),
                ('personality', models.TextField(default='Personality de la empresa')),
            ],
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(default='Servicios', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuario_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(default='Escribir nombre', max_length=100)),
                ('clave', models.CharField(default='Ingresar clave', max_length=30)),
                ('correo', models.CharField(default='Escribir email', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ingreso_wunder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_cliente.empresa')),
                ('usuario_cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_cliente.usuario_cliente')),
            ],
        ),
        migrations.CreateModel(
            name='autorizacion_servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_cliente.servicios')),
                ('usuario_cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_cliente.usuario_cliente')),
            ],
        ),
    ]
